### ISSUE TITLE
`datenum` is not defined when trying to save a Date

### ISSUE THREAD

**Issue by germanio** [waylonflinn/xlsx-workbook#7]
Hey, hope you are doing well. Nice API btw.
I was working on the generation of a report when I found this issue.
I wrote a much simpler example, based on the example you posted on the docs, just in case I were missing something, but no. Please take a look at this, it returns the error below.

```javascript

function generate_report() {
    // the Worksheet object gives you a simple interface to a single sheet
    let Worksheet = require('xlsx-workbook').Worksheet;

    let worksheet = new Worksheet("Hello Spreadsheet");

    // add data using row and column indices on the worksheet object
    worksheet[0][0] = new Date();
    worksheet[0][1] = new Date();

    // saving automatically creates a new workbook with the same name
    let workbook = worksheet.save();
}

generate_report();
```

Error:
```
$> node example.js 
/opt/dev/example/node_modules/xlsx-workbook/index.js:257
                                cell.v = datenum(cell.v);
                                         ^

ReferenceError: datenum is not defined
    at Worksheet.objectify (/opt/dev/example/node_modules/xlsx-workbook/index.js:257:14)
    at Workbook.objectify (/opt/dev/example/node_modules/xlsx-workbook/index.js:133:18)
    at Workbook.save (/opt/dev/example/node_modules/xlsx-workbook/index.js:158:12)
    at Worksheet.save (/opt/dev/example/node_modules/xlsx-workbook/index.js:279:11)
    at generate_report (/opt/dev/example/example.js:14:30)
    at Object.<anonymous> (/opt/dev/example/example.js:17:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
```

I think it's related to this part of the code, where `datenum()` is not defined, but it is defined inside `xlsx` instead.

```javascript
// set the type
if(typeof cell.v === 'number') cell.t = 'n';
else if(typeof cell.v === 'boolean') cell.t = 'b';
else if(cell.v instanceof Date) {
	cell.t = 'n'; cell.z = xlsx.SSF._table[14];
	cell.v = datenum(cell.v);
}
else cell.t = 's';
```
Quick solution? Since the `datenum` function is pretty standard and just a few lines of code, it could easily be copied to the `xlsx-workbook` file.

**Comment by germanio** [comment]
Hey @waylonflinn I have a working PR to fix this issue. Could you review it?
Thanks!

**Comment by cMurschall** [comment]
Thanks for the fix, I appreciate it a lot and it worked perfect for me.
